import unittest

import tailwag_memory
from tailwag_memory import (
    EmbeddingProvider,
    EpisodeIngestionService,
    EpisodeInput,
    EpisodeMemoryExtractionResult,
    EpisodeMemoryExtractionService,
    EpisodeMemoryResult,
    EpisodeRecordResult,
    EpisodeRetrievalService,
    EventAttendeeInput,
    EventIngestionService,
    EventInput,
    EventResult,
    EventRetrievalService,
    MemoryItemInput,
    MemoryItemResult,
    MemoryItemService,
    MockOpenAIEmbeddingProvider,
    Neo4jQueryRunner,
    OpenAIConfigurationError,
    OpenAIEmbeddingProvider,
    PersonContextItem,
    PersonContextRetrievalService,
    PersonContextSource,
    PersonContextSynthesisService,
    PersonContextTranscriptLine,
    PersonInput,
    PersonMemoryContextService,
    PersonMemoryExtractionResult,
    PersonRecognitionResult,
    PersonRecognitionService,
    PlaceInput,
    QueryRunner,
    SearchQuery,
    Settings,
    TailwagMemoryClient,
    initialize_schema,
    load_settings,
)


class PackageImportTest(unittest.TestCase):
    def test_public_facade_exports_consumer_imports(self) -> None:
        expected_exports = {
            "EmbeddingProvider",
            "EpisodeIngestionService",
            "EpisodeInput",
            "EpisodeMemoryExtractionResult",
            "EpisodeMemoryExtractionService",
            "EpisodeMemoryResult",
            "EpisodeRecordResult",
            "EpisodeRetrievalService",
            "EventAttendeeInput",
            "EventIngestionService",
            "EventInput",
            "EventResult",
            "EventRetrievalService",
            "MemoryItemInput",
            "MemoryItemResult",
            "MemoryItemService",
            "MockOpenAIEmbeddingProvider",
            "Neo4jQueryRunner",
            "OpenAIConfigurationError",
            "OpenAIEmbeddingProvider",
            "PersonContextItem",
            "PersonContextRetrievalService",
            "PersonContextSource",
            "PersonContextSynthesisService",
            "PersonContextTranscriptLine",
            "PersonInput",
            "PersonMemoryContextService",
            "PersonMemoryExtractionResult",
            "PersonRecognitionResult",
            "PersonRecognitionService",
            "PlaceInput",
            "QueryRunner",
            "SearchQuery",
            "Settings",
            "TailwagMemoryClient",
            "initialize_schema",
            "load_settings",
        }
        imported = {
            EmbeddingProvider,
            EpisodeIngestionService,
            EpisodeInput,
            EpisodeMemoryExtractionResult,
            EpisodeMemoryExtractionService,
            EpisodeMemoryResult,
            EpisodeRecordResult,
            EpisodeRetrievalService,
            EventAttendeeInput,
            EventIngestionService,
            EventInput,
            EventResult,
            EventRetrievalService,
            MemoryItemInput,
            MemoryItemResult,
            MemoryItemService,
            MockOpenAIEmbeddingProvider,
            Neo4jQueryRunner,
            OpenAIConfigurationError,
            OpenAIEmbeddingProvider,
            PersonContextItem,
            PersonContextRetrievalService,
            PersonContextSource,
            PersonContextSynthesisService,
            PersonContextTranscriptLine,
            PersonInput,
            PersonMemoryContextService,
            PersonMemoryExtractionResult,
            PersonRecognitionResult,
            PersonRecognitionService,
            PlaceInput,
            QueryRunner,
            SearchQuery,
            Settings,
            TailwagMemoryClient,
            initialize_schema,
            load_settings,
        }

        self.assertEqual(set(tailwag_memory.__all__), expected_exports)
        self.assertEqual(len(imported), len(expected_exports))
        self.assertIs(tailwag_memory.TailwagMemoryClient, TailwagMemoryClient)
        self.assertIs(tailwag_memory.Settings, Settings)
        self.assertIs(tailwag_memory.EpisodeInput, EpisodeInput)
        self.assertIs(tailwag_memory.EpisodeIngestionService, EpisodeIngestionService)
        self.assertIs(tailwag_memory.EpisodeRetrievalService, EpisodeRetrievalService)


if __name__ == "__main__":
    unittest.main()
