"""Consumer-facing public API for tailwag-memory."""

from .client import TailwagMemoryClient
from .config import Settings, load_settings
from .db import Neo4jQueryRunner, QueryRunner
from .embeddings import EmbeddingProvider, MockOpenAIEmbeddingProvider, OpenAIConfigurationError, OpenAIEmbeddingProvider
from .ingestion import EpisodeIngestionService, EventIngestionService, PersonIngestionService
from .memory_context import PersonMemoryContextService
from .memory_items import (
    DEFAULT_MIN_PATTERN_EVIDENCE_EPISODES,
    EpisodeMemoryExtractionService,
    MemoryConsolidationService,
    MemoryItemService,
    OpenAIMemoryConsolidationProvider,
)
from .models import (
    BiometricCandidate,
    BiometricEnrollmentResult,
    BiometricSearchResult,
    BiometricUpdateResult,
    DirectoryPersonRecord,
    DirectorySyncResult,
    EpisodeInput,
    EpisodeMentionInput,
    EpisodeMemoryExtractionResult,
    EpisodeMemoryResult,
    EpisodeRecordResult,
    EventAttendeeInput,
    EventInput,
    EventResult,
    IdentityCandidate,
    IdentityResolutionResult,
    MemoryItemInput,
    MemoryItemMergeResult,
    MemoryItemResult,
    MemoryConsolidationResult,
    OwnerResolutionResult,
    PersonContextItem,
    PersonContextResult,
    PersonContextSource,
    PersonContextTranscriptLine,
    PersonInput,
    PersonMemoryConsolidationResult,
    PersonMemoryExtractionResult,
    PersonProfile,
    PersonRecognitionResult,
    PlaceInput,
    SearchQuery,
    VerifiedProfile,
)
from .retrieval import (
    EpisodeRetrievalService,
    EventRetrievalService,
    PersonContextRetrievalService,
)
from .schema import initialize_schema

__all__ = [
    "EmbeddingProvider",
    "BiometricCandidate",
    "BiometricEnrollmentResult",
    "BiometricSearchResult",
    "BiometricUpdateResult",
    "DirectoryPersonRecord",
    "DirectorySyncResult",
    "EpisodeIngestionService",
    "EpisodeInput",
    "EpisodeMentionInput",
    "EpisodeMemoryExtractionResult",
    "EpisodeMemoryExtractionService",
    "EpisodeMemoryResult",
    "EpisodeRecordResult",
    "EpisodeRetrievalService",
    "EventAttendeeInput",
    "EventIngestionService",
    "EventInput",
    "EventResult",
    "EventRetrievalService",
    "IdentityCandidate",
    "IdentityResolutionResult",
    "DEFAULT_MIN_PATTERN_EVIDENCE_EPISODES",
    "MemoryConsolidationResult",
    "MemoryConsolidationService",
    "MemoryItemInput",
    "MemoryItemMergeResult",
    "MemoryItemResult",
    "MemoryItemService",
    "MockOpenAIEmbeddingProvider",
    "Neo4jQueryRunner",
    "OpenAIMemoryConsolidationProvider",
    "OpenAIConfigurationError",
    "OpenAIEmbeddingProvider",
    "OwnerResolutionResult",
    "PersonContextItem",
    "PersonContextResult",
    "PersonContextRetrievalService",
    "PersonContextSource",
    "PersonContextTranscriptLine",
    "PersonIngestionService",
    "PersonInput",
    "PersonMemoryConsolidationResult",
    "PersonMemoryContextService",
    "PersonMemoryExtractionResult",
    "PersonProfile",
    "PersonRecognitionResult",
    "PlaceInput",
    "QueryRunner",
    "SearchQuery",
    "Settings",
    "TailwagMemoryClient",
    "VerifiedProfile",
    "initialize_schema",
    "load_settings",
]
