"""Consumer-facing public API for tailwag-memory."""

from .affect import AffectScore, AffectScoringProvider, FoldEnsembleAffectProvider
from .client import TailwagMemoryClient
from .config import Settings, load_settings
from .db import Neo4jQueryRunner, QueryRunner
from .embeddings import EmbeddingProvider, MockOpenAIEmbeddingProvider, OpenAIConfigurationError, OpenAIEmbeddingProvider
from .ingestion import EpisodeIngestionService, EventIngestionService, PersonIngestionService
from .memory_context import PersonMemoryContextService
from .memory_items import (
    DEFAULT_MIN_PATTERN_EVIDENCE_EPISODES,
    EpisodeMemoryExtractionService,
    MemoryConsolidationService,
    MemoryItemService,
    OpenAIMemoryConsolidationProvider,
)
from .models import (
    EpisodeInput,
    EpisodeMentionInput,
    EpisodeMemoryExtractionResult,
    EpisodeMemoryResult,
    EpisodeRecordResult,
    EventAttendeeInput,
    EventInput,
    EventResult,
    MemoryItemInput,
    MemoryItemMergeResult,
    MemoryItemResult,
    MemoryConsolidationResult,
    PersonEpisodeAffectPoint,
    PersonEpisodeTranscriptPoint,
    PersonContextItem,
    PersonContextSource,
    PersonContextTranscriptLine,
    PersonInput,
    PersonMemoryConsolidationResult,
    PersonMemoryExtractionResult,
    PersonRecognitionResult,
    PlaceInput,
    SearchQuery,
)
from .retrieval import (
    EpisodeRetrievalService,
    EventRetrievalService,
    PersonContextRetrievalService,
    PersonEpisodeTranscriptService,
    PersonRecognitionService,
)
from .schema import initialize_schema

__all__ = [
    "AffectScore",
    "AffectScoringProvider",
    "EmbeddingProvider",
    "EpisodeIngestionService",
    "EpisodeInput",
    "EpisodeMentionInput",
    "EpisodeMemoryExtractionResult",
    "EpisodeMemoryExtractionService",
    "EpisodeMemoryResult",
    "EpisodeRecordResult",
    "EpisodeRetrievalService",
    "EventAttendeeInput",
    "EventIngestionService",
    "EventInput",
    "EventResult",
    "EventRetrievalService",
    "FoldEnsembleAffectProvider",
    "DEFAULT_MIN_PATTERN_EVIDENCE_EPISODES",
    "MemoryConsolidationResult",
    "MemoryConsolidationService",
    "MemoryItemInput",
    "MemoryItemMergeResult",
    "MemoryItemResult",
    "MemoryItemService",
    "MockOpenAIEmbeddingProvider",
    "Neo4jQueryRunner",
    "OpenAIMemoryConsolidationProvider",
    "OpenAIConfigurationError",
    "OpenAIEmbeddingProvider",
    "PersonContextItem",
    "PersonContextRetrievalService",
    "PersonContextSource",
    "PersonContextTranscriptLine",
    "PersonEpisodeAffectPoint",
    "PersonEpisodeTranscriptPoint",
    "PersonEpisodeTranscriptService",
    "PersonIngestionService",
    "PersonInput",
    "PersonMemoryConsolidationResult",
    "PersonMemoryContextService",
    "PersonMemoryExtractionResult",
    "PersonRecognitionResult",
    "PersonRecognitionService",
    "PlaceInput",
    "QueryRunner",
    "SearchQuery",
    "Settings",
    "TailwagMemoryClient",
    "initialize_schema",
    "load_settings",
]
